name: Deploy Frontend to GCP Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set default project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Build and Push Docker image
        run: gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/qa-frontend

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy qa-frontend \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/qa-frontend \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --port 8080
